### ISSUE TITLE
Не подсчитывается количество игровых часов

### ISSUE THREAD

**Issue by ViktorDee** [ViktorDee/Neto-teamproject#1]
# Описание
Несмотря на время проведённое в игре, количество игровых часов всегда составляет 0.

# Локация дефекта
https://github.com/ViktorDee/Neto-teamproject/blob/fde5e5c676ae32af01d1fc00c6925ed009bd2a55/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения
1. Клонировать [репозиторий](https://github.com/ViktorDee/Neto-teamproject) на свой компьютер
2. В IDEA открыть класс PlayerTest
3. Запустить тест https://github.com/ViktorDee/Neto-teamproject/blob/fde5e5c676ae32af01d1fc00c6925ed009bd2a55/src/test/java/ru/netology/PlayerTest.java#L9-L20
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Количество проведённых в игре часов отображается корректно
*Фактический результат:* Количество проведённых в игре часов равно 0

# Скриншот
![image](https://user-images.githubusercontent.com/115978271/219015893-9f63a92e-295e-4bb8-97e7-d6a72e5f6aeb.png)

# Окружение
* **Операционная система:** Windows10 Home
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Yulya-s-n** [comment]
# Описание
метод public int sumGenre, в классе Player, верно рассчитывает количество игровых часов
# Скриншот 
![Neto-teamproject – Player java 2023-02-28 22 27 14](https://user-images.githubusercontent.com/116459432/221959445-662f29ef-3589-409e-9127-2cda7abd3337.png)
