### ISSUE TITLE
Метод  publishGame в классе GameStore не выдает исключение

### ISSUE THREAD

**Issue by Yulya-s-n** [ViktorDee/Neto-teamproject#10]
#  Метод  publishGame в классе GameStore не выдает исключение при дублировании игры

# Локация дефекта 
https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/main/java/ru/netology/GameStore.java#L22

#  Шаги воспроизведения
1. Открыть [код программы](https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/main/java/ru/netology/GameStore.java#L22) в IDEA.
2.  Открыть и запустить [тест](https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/test/java/ru/netology/GameStoreTest.java#L50)  в IDEA.
3.  Посмотреть результат в консоли

*Ожидаемый результат:*  Метод показывает исключение
*Фактический результат:*  В консоли появляется ошибка  Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот 
![№№№№№](https://user-images.githubusercontent.com/116459432/221355400-7e4fee45-d6e3-45ec-ac76-c03713416612.png)

# Окружение

* **Операционная система:**  Windows 10 Home
* **IDE:**  IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by ViktorDee** [comment]
# Скриншот

![image](https://user-images.githubusercontent.com/115978271/222164241-1415cb2d-d3c4-434f-8dd9-1f8e64c5bbd3.png)

# Окружение
* **Операционная система:** Windows 10 Home
* **IDE:**  IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA: ** OpenJDK 11
