### ISSUE TITLE
в методе  addPlayTime в классе GameStore не суммируется время

### ISSUE THREAD

**Issue by Yulya-s-n** [ViktorDee/Neto-teamproject#11]
# В методе  addPlayTime в классе GameStore не суммируется время с прошлым значением для этого игрока

# Локация дефекта
https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/main/java/ru/netology/GameStore.java#L46

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/main/java/ru/netology/GameStore.java#L46) в IDEA
2. Открыть и запустить [тест](https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/test/java/ru/netology/GameStoreTest.java#L34) в IDEA
3. Посмотреть результат в консоли

*Ожидаемый результат:* 10
*Фактический результат:*  0 

# Скриншот 
![000000](https://user-images.githubusercontent.com/116459432/221357480-8ffeb468-1865-4277-9800-9d524feb3467.png)

# Окружение

* **Операционная система:**  Windows 10 Home
* **IDE:**  IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by ViktorDee** [comment]
# Скриншот 
![image](https://user-images.githubusercontent.com/115978271/222164507-af0ae290-e396-42ac-a820-09f9b94e4fde.png)


# Окружение

* **Операционная система:**  Windows 10 Home
* **IDE:**  IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA:** OpenJDK 11
