### ISSUE TITLE
Приложение выдаёт ошибку вместо сообщения о том, что игра не установлена

### ISSUE THREAD

**Issue by ViktorDee** [ViktorDee/Neto-teamproject#2]
# Описание
При попытке узнать количество часов проведённых в неустановленной игре, приложение выдаёт ошибку вместо сообщения о том, что игра не установлена.

# Локация дефекта
https://github.com/ViktorDee/Neto-teamproject/blob/fde5e5c676ae32af01d1fc00c6925ed009bd2a55/src/main/java/ru/netology/Player.java#L24-L26

# Шаги воспроизведения
1. Клонировать [репозиторий](https://github.com/ViktorDee/Neto-teamproject) на свой компьютер
2. В GitBash переключиться на ветку gamestore
3. В IDEA открыть класс PlayerTest
4. Запустить тест https://github.com/ViktorDee/Neto-teamproject/blob/2c405d9dc0d79a7d3e6f6532d630ebb10d7a6fc1/src/test/java/ru/netology/PlayerTest.java#L57-L68
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения о том, что игра не установлена
*Фактический результат:* Появляется ошибка "Expected java.lang.RuntimeException to be thrown, but nothing was thrown."

# Скриншот
![image](https://user-images.githubusercontent.com/115978271/219021787-d823cd1f-b571-4409-bc3f-60287c6bce48.png)

# Окружение
* **Операционная система:** Windows10 Home
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Yulya-s-n** [comment]
# Описание
Для того, чтобы программа указывала количество часов проведённых в неустановленной игре и, что игра не установлена  исправлен [метод play в классе Player](https://github.com/ViktorDee/Neto-teamproject/blob/1be45fbee5f788149467e915a6f9cadddc053afa/src/main/java/ru/netology/Player.java#L39)
# Скриншот
![22](https://user-images.githubusercontent.com/116459432/222244828-91cf8e03-25a2-40f6-9588-bd9523a1a4ed.png)
![2222](https://user-images.githubusercontent.com/116459432/222244846-6ba9323f-054b-40ed-aad7-80fe3d3b767c.png)
