### ISSUE TITLE
При проверке наличия игр в каталоге метод GameStore возвращает не верный ответ

### ISSUE THREAD

**Issue by Yulya-s-n** [ViktorDee/Neto-teamproject#3]
# Описание

Тест не проходит в методе GameStore при прохождении цикла "public boolean containsGame(Game game)"

# Локация дефекта

https://github.com/ViktorDee/Neto-teamproject/blob/fe5cf7a6e011085153f8cc95ae9985d076584f59/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/ViktorDee/Neto-teamproject/tree/gamestore) в IDEA
2.  Запустить [GameStoreTest](https://github.com/ViktorDee/Neto-teamproject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java)
3.  Сравнить ожидаемый результат и фактический в консоли IDEA

*Ожидаемый результат:* вывод сообщения, что тест прошел
*Фактический результат:* вывод сообщения, тест не прошел

# Скриншот

![!!!!](https://user-images.githubusercontent.com/116459432/219480324-ee95ccfa-ee68-4491-95cf-e3e86a230e19.png)

# Окружение

* **Операционная система:**  Windows 10 Home
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by ViktorDee** [comment]
# Скриншот

![image](https://user-images.githubusercontent.com/115978271/222163413-008a11c2-e9a5-472f-b2c4-ba07d609d1fa.png)

# Окружение

* **Операционная система:**  Windows 10 Home
* **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA:** OpenJDK 11
