### ISSUE TITLE
Игра с наибольшим количеством игрового времени не определяется

### ISSUE THREAD

**Issue by ViktorDee** [ViktorDee/Neto-teamproject#4]
# Описание
При попытке по жанру определить игру с наибольшим количеством игрового времени программа выдаёт сообщение "null"

# Локация дефекта
https://github.com/ViktorDee/Neto-teamproject/blob/fe5cf7a6e011085153f8cc95ae9985d076584f59/src/main/java/ru/netology/Player.java#L59-L60

# Шаги воспроизведения
1. Клонировать [репозиторий](https://github.com/ViktorDee/Neto-teamproject) на свой компьютер
2. В GitBash переключиться на ветку gamestore
3. В IDEA открыть класс PlayerTest
4. Запустить тест https://github.com/ViktorDee/Neto-teamproject/blob/fe5cf7a6e011085153f8cc95ae9985d076584f59/src/test/java/ru/netology/PlayerTest.java#L85-L109
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод названия игры "Шахматы" 
*Фактический результат:* Появляется сообщение "null"

# Скриншот
![image](https://user-images.githubusercontent.com/115978271/219630021-9162202b-f57e-4a1c-8211-1aa94c1628ee.png)

# Окружение
* **Операционная система:** Windows10 Home
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Yulya-s-n** [comment]
# Описание
Метод принимает жанр и возвращает игру этого жанра, в которую играли больше всего. Если в игры этого жанра не играли, возвращается null
# Скриншот
![!!!!!!!](https://user-images.githubusercontent.com/116459432/222238024-227a5f68-ff41-4e6b-92f4-b88ee81b3a3e.png)
![!!!!!!](https://user-images.githubusercontent.com/116459432/222238040-14746039-996c-4ac5-bc21-b227edc31198.png)
