### ISSUE TITLE
Метод GameStore не суммирует  общее количество времени всех игроков

### ISSUE THREAD

**Issue by Yulya-s-n** [ViktorDee/Neto-teamproject#9]
# Метод GameStore не суммирует  общее количество времени всех игроков, проведённого за играми этого каталога

# Локация дефекта
https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/main/java/ru/netology/GameStore.java#L75

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/main/java/ru/netology/GameStore.java#L75) в IDEA
2.  Открыть и запустить [тест](https://github.com/ViktorDee/Neto-teamproject/blob/6d110239b7054f9e77865b2bbcbfefdbbfa00b94/src/test/java/ru/netology/GameStoreTest.java#L19) в IDEA
3.  Посмотреть результат в консоли

*Ожидаемый результат:*  3 часа
*Фактический результат:*  0 часов

# Скриншот

![Neto-teamproject – GameStoreTest java 2023-02-25 1](https://user-images.githubusercontent.com/116459432/221354248-adde27ef-6a34-4bae-b36c-8b815f01b8de.png)

# Окружение
* **Операционная система:** Windows 10 Home
* **IDE:**  IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA: ** OpenJDK 11

**Comment by ViktorDee** [comment]
# Скриншот

![image](https://user-images.githubusercontent.com/115978271/222163921-086e44f3-a0aa-40ea-ab12-1bfc7ae330f4.png)

# Окружение
* **Операционная система:** Windows 10 Home
* **IDE:**  IntelliJ IDEA 2022.2.3 (Community Edition)
* **JAVA: ** OpenJDK 11
